version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: for_sql_python
    restart: always
    ports: 
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'db'
      # root-nya diganti jadi user
      MYSQL_USER: 'user'
      # password untuk MYSQL_USER diatas
      MYSQL_PASSWORD: 'password'
      # password untuk root
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
